#!/bin/bash

set -e

# Save current folder and change directory to HOME
currentFolder=$(pwd)
cd "$HOME"

pacman -Syu

# System
pacman -S     \
  tldr        \
  ripgrep     \
  latte-dock  \
  git         \
  fzf         \
  flatpak     \
  python      \
  nodejs      \
  npm         \
  fd          \
  bat         \
  make        \
  kvantum     \
  duf         \
  zip         \
  unzip       \
  bashtop     \
  firefox     \
  python-pip

# fzf shortcuts
# junegunn/fzf-git.sh
# clona na pasta /opt antes de dar um source no .bashrc

# Neovim
pacman -S       \
  neovim        \
  python-pynvim \
  python-black  \
  flake8        \
  pyright       \
  prettier      \
  shfmt         \
  shellcheck    \
  stylua        \
  tolua++       \
  clang         \
  ncdu          \
  zk            \
  lldb          \
  mercurial     \
  luarocks      \
  composer      \
  julia         \
  chafa

# Terminal customization
pacman -S   \
  starship  \
  alacritty \
  tmux      \
  ueberzug  \
  playerctl \
  exa
  # tmux-mem-cpu-load
  # https://github.com/thewtex/tmux-mem-cpu-load/
  # git clone git@github.com:thewtex/tmux-mem-cpu-load.git
  # sudo mv tmux-mem-cpu-load /opt/
  # cd /opt/tmux-mem-cpu-load/
  # cmake . && make && sudo make install

# Development
pacman -S \
  cmake   \
  docker  \
  docker-compose \
  catch2

# conventional-changelog/commitlint
# clona na pasta /opt
# dentro da pasta /opt/commitlint roda: yarn && yarn run build
# procura alguma configuração padrão no site para adicionar ao repo e altera o
# arquivo `commitlint.config.js` de `exports default` -> `module.exports = `

# SGDK
# yay -S \
#   blastem \
#   bizhawk-monort

# Utils
pacman -S \
  obs-studio \
  kdenlive \
  discord \
  spotify-launcher \
  spotifyd \
  timeshift

# Games
pacman -S \
  steam

# Install yay
# git clone https://aur.archlinux.org/yay.git
# sudo mv yay /opt/
# cd /opt/yay
# makepkg -si
# cd "$HOME"

cd "$currentFolder"

