#!/bin/bash

set -e

# Save current folder and change directory to HOME
currentFolder=$(pwd)
cd "$HOME"

pacman -Syu

# System
pacman -S --needed \
  tldr             \
  ripgrep          \
  latte-dock       \
  git              \
  fzf              \
  flatpak          \
  npm              \
  fd               \
  bat              \
  make             \
  kvantum          \
  duf              \
  zip              \
  unzip            \
  bashtop          \
  firefox          \
  git-delta        \
  thefuck          \
  zoxide           \
  glow             \
  gum              \
  vhs

# fzf shortcuts
# junegunn/fzf-git.sh
# clona na pasta /opt antes de dar um source no .bashrc

# Neovim
pacman -S --needed \
  neovim           \
  python-pynvim    \
  python-black     \
  python-debugpy   \
  flake8           \
  pyright          \
  prettier         \
  shfmt            \
  shellcheck       \
  stylua           \
  tolua++          \
  clang            \
  ncdu             \
  zk               \
  lldb             \
  mercurial        \
  luarocks         \
  composer         \
  julia            \
  chafa            \
  delve

# Terminal customization
pacman -S --needed \
  starship         \
  alacritty        \
  tmux             \
  ueberzug         \
  playerctl        \
  eza
  # tmux tpm
  # git clone git@github.com:tmux-plugins/tpm.git ~/.tmux/plugins/tpm

  # tmuxifier
  # git clone git@github.com:jimeh/tmuxifier.git ~/.tmuxifier

# Development
pacman -S --needed \
  cmake            \
  nodejs           \
  python           \
  python-pip       \
  docker           \
  docker-compose   \
  catch2           \
  go
  # go install github.com/charmbracelet/mods@latest
  # go install github.com/charmbracelet/soft-serve/cmd/soft@latest
  # querystack
  # git clone git@github.com:felipe-goes/querystack.git
  # cd querystack && go build . && mv querystack $HOME/go/bin/

# conventional-changelog/commitlint
# clona na pasta /opt
# dentro da pasta /opt/commitlint roda: yarn && yarn run build
# procura alguma configuração padrão no site para adicionar ao repo e altera o
# arquivo `commitlint.config.js` de `exports default` -> `module.exports = `

# SGDK
# yay -S \
#   blastem \
#   bizhawk-monort

# Utils
pacman -S --needed \
  obs-studio       \
  kdenlive         \
  discord          \
  spotify-launcher \
  spotifyd         \
  timeshift

# Games
pacman -S --needed steam

# Install yay
# git clone https://aur.archlinux.org/yay.git
# sudo mv yay /opt/
# cd /opt/yay
# makepkg -si
# cd "$HOME"

cd "$currentFolder"

