#!/usr/bin/bash

set -e

flag=$1

if [[ $flag == "clean" ]]; then
  rm -rf "$PWD"/out "$PWD"/src/boot "$PWD"/res/resources.h
elif [[ $flag == "cmake" ]]; then
  cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && rm -rf cmake_install.cmake CMakeCache.txt CMakeFiles/ Makefile
else
  docker run --rm -v "$PWD":/m68k -t \
    registry.gitlab.com/doragasu/docker-sgdk:v1.70

  if [[ $flag == "blastem" ]]; then
    blastem "$PWD"/out/rom.bin
  elif [[ $flag == "bizhawk" ]]; then
    bizhawk "$PWD"/out/rom.bin
  fi
fi
