#!/usr/bin/bash

set -e

flag=$1

if [[ "$flag" == "clean" ]]; then
  docker run --rm -v "$PWD":/m68k -t \
    registry.gitlab.com/doragasu/docker-sgdk:v1.80 clean
else
  docker run --rm -v "$PWD":/m68k -t \
    registry.gitlab.com/doragasu/docker-sgdk:v1.80

  if [[ "$flag" == "blastem" ]]; then
    blastem "$PWD"/out/rom.bin
  elif [[ "$flag" == "bizhawk" ]]; then
    bizhawk "$PWD"/out/rom.bin
  fi
fi
