#!/usr/bin/bash
# Faz todos os processos necessários para converter o episódio de anime para
# ficar compatível com a TV.

video="mkv"
audio="flac"
sub="ass"
audiotrack=2
subtrack=3

exdata $audio $sub $audiotrack $subtrack
# editsub
attaudio $video $audio

mv ./*."$sub" ./out || exit
(
  cd ./out || exit
  attsub "$video" "$sub"
)
