#!/usr/bin/bash
# Anexa audio nos vídeos da pasta atual. O vídeo de saída é criado dentro de uma
# pasta que já deveria ter sido criada previamente chamada out. O nome do vídeo
# tem que ser igual ao nome do audio.
# Sintaxe: attaudio <formato_do_video> <formato_do_audio>

video=$1
audio=$2

/usr/bin/ls -l --quoting-style=literal | tr -s ' ' | cut -d ' ' -f 9- |
  grep "$video" | tr -s '.' | cut -d '.' -f -1 | sed '/^[[:space:]]*$/d' |
  xargs -I _ ffmpeg -i _."$video" -i _."$audio" -map 0:v -map 1:a -c:v copy -shortest ./out/_."$video"
