#!/usr/bin/bash

project=$1

if [ -n "$project" ]; then
	mkdir -p cmake-"$project"/
	cp -a "$HOME"/Templates/cmake-"$project"/. cmake-"$project"/
else
	mkdir -p cmake-template/
	cp -a "$HOME"/Templates/cmake-template/. cmake-template/
fi
