#!/usr/bin/bash

# Pen stylus
xsetwacom set "Wacom Intuos PT S 2 Pen stylus" MapToOutput "eDP1"
xsetwacom set "Wacom Intuos PT S 2 Pen stylus" TabletPCButton "on"
xsetwacom set "Wacom Intuos PT S 2 Pen stylus" Mode "Absolute"
xsetwacom set "Wacom Intuos PT S 2 Pen stylus" PanScrollThreshold 1400

# Finger touch
xsetwacom set "Wacom Intuos PT S 2 Finger touch" Touch off

# Pad pad

